import fs from "node:fs";
import path from "node:path";

import type { School } from "@/lib/types";
import {
  buildSchoolAliases,
  deriveSchoolShortName,
  normalizeSchoolText,
} from "@/lib/school-display";

/** Primary path used by local ETL (`import_school_directory`). */
export const SCORECARD_DIRECTORY_JSON_PATH = path.join(
  process.cwd(),
  "etl",
  "output",
  "college_scorecard_schools.json",
);

/** Committed fallback bundled with the app (e.g. Vercel) when `etl/output` is absent. */
export const SCORECARD_DIRECTORY_DATA_BUNDLE_PATH = path.join(
  process.cwd(),
  "data",
  "college_scorecard_schools.json",
);

function resolveScorecardDirectoryJsonFile(): string | null {
  const fromEnv = process.env.SCORECARD_DIRECTORY_JSON_PATH?.trim();
  if (fromEnv && fs.existsSync(fromEnv)) {
    return fromEnv;
  }
  if (fs.existsSync(SCORECARD_DIRECTORY_JSON_PATH)) {
    return SCORECARD_DIRECTORY_JSON_PATH;
  }
  if (fs.existsSync(SCORECARD_DIRECTORY_DATA_BUNDLE_PATH)) {
    return SCORECARD_DIRECTORY_DATA_BUNDLE_PATH;
  }
  return null;
}

/** Raw row shape written by `etl.scripts.import_school_directory`. */
export type ScorecardDirectoryRecord = {
  school_id: number;
  slug: string;
  name: string;
  alias?: string | null;
  city: string;
  state: string;
  website?: string | null;
  control?: string | null;
  student_size?: number | null;
};

export const SCORECARD_SCHOOL_SLUG_CANONICAL: Record<string, string> = {
  "the-university-of-texas-at-austin": "ut-austin",
  "the-university-of-texas-at-arlington": "ut-arlington",
  "the-university-of-texas-at-dallas": "ut-dallas",
  "the-university-of-texas-at-el-paso": "ut-el-paso",
  "the-university-of-texas-at-san-antonio": "ut-san-antonio",
  "the-university-of-texas-at-tyler": "ut-tyler",
  "texas-a-m-university-college-station": "texas-am",
  "the-university-of-texas-rio-grande-valley": "ut-rio-grande-valley",
  "the-university-of-texas-permian-basin": "ut-permian-basin",
  "arizona-state-university-campus-immersion": "asu",
  "university-of-california-berkeley": "uc-berkeley",
  "university-of-wisconsin-madison": "uw-madison",
  "the-ohio-state-university-main-campus": "ohio-state",
  "ohio-state-university-main-campus": "ohio-state",
  "ohio-university-main-campus": "ohio-university",
  "bowling-green-state-university-main-campus": "bowling-green-state-university",
  "north-carolina-state-university-at-raleigh": "north-carolina-state-university",
  "university-of-north-carolina-at-chapel-hill": "unc-chapel-hill",
  "university-of-washington-seattle-campus": "university-of-washington",
  "university-of-illinois-urbana-champaign": "uiuc",
  "georgia-institute-of-technology-main-campus": "georgia-tech",
  "university-of-michigan-ann-arbor": "umich",
  "university-of-california-los-angeles": "ucla",
  "university-of-california-san-diego": "uc-san-diego",
  "university-of-california-davis": "uc-davis",
  "university-of-california-irvine": "uc-irvine",
  "university-of-california-riverside": "uc-riverside",
  "university-of-california-santa-cruz": "uc-santa-cruz",
  "university-of-california-merced": "uc-merced",
  "university-of-california-san-francisco": "uc-san-francisco",
  "university-of-california-santa-barbara": "uc-santa-barbara",
  "the-university-of-alabama": "university-of-alabama",
  "virginia-polytechnic-institute-and-state-university": "virginia-tech",
  "southern-methodist-university": "smu",
  "stanford-university": "stanford",
  "massachusetts-institute-of-technology": "mit",
  "yale-university": "yale",
  "harvard-university": "harvard",
  "duke-university": "duke",
  "northwestern-university": "northwestern",
  "university-of-southern-california": "usc",
  "cornell-university": "cornell",
  "columbia-university-in-the-city-of-new-york": "columbia",
  "university-of-pennsylvania": "upenn",
  "princeton-university": "princeton",
  "brown-university": "brown",
  "dartmouth-college": "dartmouth",
  "johns-hopkins-university": "johns-hopkins",
  "new-york-university": "nyu",
  "carnegie-mellon-university": "cmu",
  "university-of-notre-dame": "notre-dame",
  "vanderbilt-university": "vanderbilt",
  "rice-university": "rice",
  "georgetown-university": "georgetown",
  "university-of-virginia-main-campus": "uva",
  "pennsylvania-state-university-main-campus": "penn-state",
  "purdue-university-main-campus": "purdue",
  "university-of-florida": "uf",
  "university-of-minnesota-twin-cities": "minnesota",
  "arizona-state-university-tempe": "asu",
  "university-of-central-florida": "university-of-central-florida",
  "florida-international-university": "florida-international-university",
  "university-of-south-florida": "university-of-south-florida",
  "indiana-university-bloomington": "indiana-university-bloomington",
  "university-of-houston": "university-of-houston",
  "university-of-north-texas": "university-of-north-texas",
  "kennesaw-state-university": "kennesaw-state-university",
  "utah-valley-university": "utah-valley-university",
  "florida-state-university": "florida-state-university",
  "california-state-university-fullerton": "california-state-university-fullerton",
  "california-state-university-northridge": "california-state-university-northridge",
  "university-of-georgia": "university-of-georgia",
  "texas-tech-university": "texas-tech-university",
  "texas-state-university": "texas-state-university",
  "george-mason-university": "george-mason-university",
  "california-state-university-long-beach": "california-state-university-long-beach",
  "michigan-state-university": "michigan-state-university",
  "georgia-state-university": "georgia-state-university",
  "iowa-state-university": "iowa-state-university",
  "baylor-university": "baylor-university",
  "university-of-arizona": "university-of-arizona",
  "rutgers-university-new-brunswick": "rutgers-university-new-brunswick",
  "university-of-south-carolina-columbia": "university-of-south-carolina-columbia",
  "auburn-university": "auburn-university",
  "university-at-buffalo": "university-at-buffalo",
  "oregon-state-university": "oregon-state-university",
  "university-of-utah": "university-of-utah",
  "university-of-north-carolina-at-charlotte": "university-of-north-carolina-at-charlotte",
  "east-carolina-university": "east-carolina-university",
  "university-of-cincinnati-main-campus": "university-of-cincinnati",
  "university-of-maryland-college-park": "university-of-maryland-college-park",
  "university-of-kansas": "university-of-kansas",
  "university-of-missouri-columbia": "university-of-missouri",
  "the-university-of-tennessee-knoxville": "the-university-of-tennessee-knoxville",
  "university-of-kentucky": "university-of-kentucky",
  "university-of-oklahoma-norman-campus": "university-of-oklahoma",
  "university-of-arkansas": "university-of-arkansas",
  "university-of-nevada-las-vegas": "university-of-nevada-las-vegas",
  "university-of-mississippi": "university-of-mississippi",
  "university-of-colorado-boulder": "cu-boulder",
  "university-of-iowa": "iowa",
  "boston-university": "bu",
  "northeastern-university": "northeastern",
  "the-university-of-montana": "university-of-montana",
  "university-of-new-mexico-main-campus": "university-of-new-mexico",
  "university-of-new-hampshire-main-campus": "university-of-new-hampshire",
  "university-of-massachusetts-medical-school-worcester":
    "university-of-massachusetts-chan-medical-school",
};

const SCORECARD_SCHOOL_ALIAS_EXTRAS: Record<string, string[]> = {
  "ut-austin": ["UT", "UT Austin", "University of Texas", "Texas Austin"],
  "ut-arlington": ["UT Arlington", "UTA", "University of Texas at Arlington"],
  "ut-dallas": ["UT Dallas", "UTD", "University of Texas at Dallas"],
  "ut-el-paso": ["UTEP", "UT El Paso", "University of Texas at El Paso"],
  "ut-san-antonio": ["UTSA", "UT San Antonio", "University of Texas at San Antonio"],
  "ut-tyler": ["UT Tyler", "University of Texas at Tyler"],
  "ut-rio-grande-valley": ["UTRGV", "UT Rio Grande Valley", "University of Texas Rio Grande Valley"],
  "ut-permian-basin": ["UT Permian Basin", "UTPB", "University of Texas Permian Basin"],
  asu: ["ASU", "Arizona State", "Arizona State University", "ASU Tempe"],
  "texas-am": ["Texas A&M", "Texas A and M", "TAMU", "A&M", "Texas AM"],
  "uc-berkeley": ["UC Berkeley", "Berkeley", "Cal"],
  "ucla": ["UCLA", "UC Los Angeles"],
  "uc-san-diego": ["UC San Diego", "UCSD", "San Diego"],
  "uc-davis": ["UC Davis", "Davis"],
  "uc-irvine": ["UC Irvine", "UCI", "Irvine"],
  "uc-riverside": ["UC Riverside", "UCR", "Riverside"],
  "uc-santa-barbara": ["UC Santa Barbara", "UCSB", "Santa Barbara"],
  "uc-santa-cruz": ["UC Santa Cruz", "UCSC", "Santa Cruz"],
  "uc-merced": ["UC Merced", "Merced"],
  "uc-san-francisco": ["UC San Francisco", "UCSF", "San Francisco"],
  brown: ["Brown University", "Brown"],
  dartmouth: ["Dartmouth College", "Dartmouth"],
  "uw-madison": ["UW-Madison", "UW Madison", "Wisconsin", "Madison"],
  "ohio-state": ["Ohio State", "OSU", "The Ohio State University"],
  "unc-chapel-hill": ["UNC", "UNC Chapel Hill", "Carolina"],
  "university-of-washington": ["UW", "University of Washington", "Washington Seattle"],
  uiuc: ["UIUC", "Illinois", "U of I", "University of Illinois"],
  "western-governors-university": ["Western Governors University", "WGU"],
  "southern-new-hampshire-university": ["SNHU", "Southern New Hampshire University"],
  "grand-canyon-university": ["GCU", "Grand Canyon University"],
  "liberty-university": ["Liberty", "Liberty University"],
  "university-of-phoenix-arizona": ["University of Phoenix-Arizona", "University of Phoenix Arizona", "Phoenix Arizona"],
  "lone-star-college-system": ["Lone Star College", "Lone Star College System"],
  "university-of-central-florida": ["UCF", "University of Central Florida"],
  "florida-international-university": ["FIU", "Florida International University"],
  "university-of-south-florida": ["USF", "University of South Florida"],
  "north-carolina-state-university": ["NC State", "NC State University", "North Carolina State University"],
  "virginia-tech": ["Virginia Tech", "Virginia Polytechnic Institute and State University"],
  "indiana-university-bloomington": ["IU Bloomington", "Indiana University Bloomington", "IUB"],
  "university-of-houston": ["UH", "University of Houston"],
  "university-of-north-texas": ["UNT", "University of North Texas", "North Texas"],
  "kennesaw-state-university": ["KSU", "Kennesaw State University"],
  "utah-valley-university": ["UVU", "Utah Valley University"],
  "florida-state-university": ["FSU", "Florida State", "Florida State University"],
  "california-state-university-fullerton": ["Cal State Fullerton", "CSUF", "California State University Fullerton"],
  "california-state-university-northridge": ["CSUN", "California State University Northridge"],
  "university-of-georgia": ["University of Georgia", "UGA"],
  "texas-tech-university": ["Texas Tech", "Texas Tech University"],
  "university-of-alabama": ["University of Alabama", "Alabama", "UA"],
  "texas-state-university": ["Texas State", "Texas State University"],
  "george-mason-university": ["George Mason", "George Mason University", "GMU"],
  "california-state-university-long-beach": ["Cal State Long Beach", "CSULB", "California State University Long Beach"],
  "michigan-state-university": ["Michigan State", "MSU", "Michigan State University"],
  "georgia-state-university": ["Georgia State", "Georgia State University"],
  "miami-dade-college": ["Miami Dade College", "MDC"],
  "iowa-state-university": ["Iowa State", "Iowa State University", "ISU"],
  "baylor-university": ["Baylor", "Baylor University"],
  "university-of-arizona": ["UArizona", "University of Arizona", "Arizona"],
  "rutgers-university-new-brunswick": ["Rutgers", "Rutgers New Brunswick", "Rutgers-New Brunswick"],
  "university-of-south-carolina-columbia": ["University of South Carolina", "South Carolina", "USC Columbia"],
  "auburn-university": ["Auburn", "Auburn University"],
  "university-at-buffalo": ["University at Buffalo", "SUNY Buffalo", "Buffalo"],
  "oregon-state-university": ["Oregon State", "Oregon State University", "OSU"],
  "university-of-utah": ["The U", "University of Utah", "Utah"],
  "university-of-north-carolina-at-charlotte": ["UNC Charlotte", "Charlotte"],
  "east-carolina-university": ["ECU", "East Carolina University"],
  "university-of-cincinnati": ["University of Cincinnati", "Cincinnati", "UC"],
  "university-of-maryland-college-park": ["University of Maryland", "UMD", "Maryland"],
  "university-of-kansas": ["University of Kansas", "Kansas", "KU"],
  "university-of-missouri": ["University of Missouri", "Mizzou", "Missouri"],
  "the-university-of-tennessee-knoxville": ["University of Tennessee", "Tennessee", "UT Knoxville"],
  "university-of-kentucky": ["University of Kentucky", "Kentucky", "UK"],
  "university-of-oklahoma": ["University of Oklahoma", "Oklahoma", "OU"],
  "university-of-arkansas": ["University of Arkansas", "Arkansas"],
  "university-of-nevada-las-vegas": ["UNLV", "University of Nevada Las Vegas"],
  "university-of-mississippi": ["Ole Miss", "University of Mississippi"],
  "university-of-delaware": ["University of Delaware", "Delaware", "UD"],
  "university-of-connecticut": ["University of Connecticut", "UConn", "Connecticut"],
  "university-of-nebraska-lincoln": ["University of Nebraska-Lincoln", "Nebraska", "UNL"],
  "university-of-new-mexico": ["University of New Mexico", "UNM", "New Mexico"],
  "university-of-alabama-at-birmingham": ["University of Alabama at Birmingham", "UAB"],
  "university-of-south-alabama": ["University of South Alabama", "South Alabama", "USA"],
  "university-of-louisville": ["University of Louisville", "Louisville", "UofL"],
  "university-of-idaho": ["University of Idaho", "Idaho", "U of I"],
  "university-of-rhode-island": ["University of Rhode Island", "URI", "Rhode Island"],
  "university-of-maine": ["University of Maine", "Maine", "UMaine"],
  "university-of-montana": ["University of Montana", "Montana", "UM"],
  "university-of-wyoming": ["University of Wyoming", "Wyoming", "UWyo"],
  "university-of-alaska-anchorage": ["University of Alaska Anchorage", "UAA", "Alaska Anchorage"],
  "university-of-alaska-fairbanks": ["University of Alaska Fairbanks", "UAF", "Alaska Fairbanks"],
  "university-of-north-dakota": ["University of North Dakota", "UND", "North Dakota"],
  "university-of-south-dakota": ["University of South Dakota", "USD", "South Dakota"],
  "university-of-vermont": ["University of Vermont", "UVM", "Vermont"],
  "university-of-new-hampshire": ["University of New Hampshire", "UNH", "New Hampshire"],
  "university-of-nevada-reno": ["University of Nevada Reno", "UNR", "Nevada Reno"],
  "university-of-hawaii-at-manoa": ["University of Hawaii at Manoa", "UH Manoa", "Hawaii Manoa"],
  "university-of-massachusetts-amherst": ["University of Massachusetts Amherst", "UMass Amherst"],
  "university-of-massachusetts-lowell": ["University of Massachusetts Lowell", "UMass Lowell"],
  "university-of-massachusetts-boston": ["University of Massachusetts Boston", "UMass Boston"],
  "university-of-massachusetts-dartmouth": ["University of Massachusetts Dartmouth", "UMass Dartmouth"],
  "university-of-massachusetts-chan-medical-school": [
    "University of Massachusetts Chan Medical School",
    "University of Massachusetts Medical School",
    "UMass Chan",
  ],
  "university-of-wisconsin-milwaukee": ["University of Wisconsin Milwaukee", "UW Milwaukee", "UWM"],
  "university-of-wisconsin-oshkosh": ["University of Wisconsin Oshkosh", "UW Oshkosh", "UWO"],
  "university-of-wisconsin-eau-claire": ["University of Wisconsin Eau Claire", "UW Eau Claire", "UWEC"],
  "university-of-wisconsin-la-crosse": ["University of Wisconsin La Crosse", "UW La Crosse", "UWL"],
  "university-of-wisconsin-whitewater": ["University of Wisconsin Whitewater", "UW Whitewater", "UWW"],
  "university-of-wisconsin-green-bay": ["University of Wisconsin Green Bay", "UW Green Bay", "UWGB"],
  "university-of-wisconsin-stevens-point": ["University of Wisconsin Stevens Point", "UW Stevens Point", "UWSP"],
  "university-of-wisconsin-stout": ["University of Wisconsin Stout", "UW Stout"],
  "university-of-wisconsin-parkside": ["University of Wisconsin Parkside", "UW Parkside"],
  "university-of-wisconsin-river-falls": ["University of Wisconsin River Falls", "UW River Falls", "UWRF"],
  "university-of-wisconsin-superior": ["University of Wisconsin Superior", "UW Superior"],
  "university-of-wisconsin-platteville": ["University of Wisconsin Platteville", "UW Platteville", "UWP"],
  "san-jose-state-university": ["San Jose State University", "San Jose State", "SJSU"],
  "california-polytechnic-state-university-san-luis-obispo": [
    "California Polytechnic State University",
    "California Polytechnic State University San Luis Obispo",
    "Cal Poly San Luis Obispo",
    "Cal Poly SLO",
  ],
  "california-state-university-sacramento": ["California State University Sacramento", "Sac State", "CSUS"],
  "california-state-university-san-bernardino": ["California State University San Bernardino", "CSUSB"],
  "california-state-university-fresno": ["California State University Fresno", "Fresno State", "CSUFresno"],
  "california-state-university-east-bay": ["California State University East Bay", "Cal State East Bay", "CSUEB"],
  "california-state-university-chico": ["California State University Chico", "Chico State"],
  "california-state-university-bakersfield": ["California State University Bakersfield", "CSUB", "Cal State Bakersfield"],
  "california-state-university-dominguez-hills": ["California State University Dominguez Hills", "CSUDH"],
  "california-state-university-channel-islands": ["California State University Channel Islands", "CSUCI"],
  "california-state-university-monterey-bay": ["California State University Monterey Bay", "CSUMB"],
  "california-state-university-stanislaus": ["California State University Stanislaus", "Stanislaus State"],
  "california-state-polytechnic-university-pomona": ["California State Polytechnic University Pomona", "Cal Poly Pomona", "CPP"],
  "california-state-university-san-marcos": ["California State University San Marcos", "CSUSM"],
  "california-state-university-los-angeles": ["California State University Los Angeles", "Cal State LA", "CSULA"],
  "san-francisco-state-university": ["San Francisco State University", "SFSU", "San Francisco State"],
  "sonoma-state-university": ["Sonoma State University", "SSU", "Sonoma State"],
  "california-state-polytechnic-university-humboldt": [
    "Cal Poly Humboldt",
    "California State Polytechnic University Humboldt",
    "Humboldt State University",
    "Humboldt State",
  ],
  "california-state-university-maritime-academy": [
    "California Maritime Academy",
    "Cal Maritime",
    "California State University Maritime Academy",
  ],
  "university-of-the-pacific": ["University of the Pacific", "Pacific"],
  "santa-clara-university": ["Santa Clara University", "SCU", "Santa Clara"],
  "pepperdine-university": ["Pepperdine University", "Pepperdine"],
  "loyola-marymount-university": ["Loyola Marymount University", "LMU", "Loyola Marymount"],
  "university-of-san-diego": ["University of San Diego", "USD"],
  "chapman-university": ["Chapman University", "Chapman"],
  "california-institute-of-technology": ["California Institute of Technology", "Caltech"],
  "harvey-mudd-college": ["Harvey Mudd College", "Harvey Mudd"],
  "pomona-college": ["Pomona College", "Pomona"],
  "claremont-mckenna-college": ["Claremont McKenna College", "CMC", "Claremont McKenna"],
  "scripps-college": ["Scripps College", "Scripps"],
  "pitzer-college": ["Pitzer College", "Pitzer"],
  "university-of-chicago": ["University of Chicago", "UChicago", "Chicago"],
  duke: ["Duke University", "Duke"],
  northwestern: ["Northwestern University", "Northwestern"],
  "johns-hopkins": ["Johns Hopkins University", "Hopkins", "JHU"],
  vanderbilt: ["Vanderbilt University", "Vanderbilt"],
  rice: ["Rice University", "Rice"],
  "notre-dame": ["University of Notre Dame", "Notre Dame"],
  cmu: ["Carnegie Mellon University", "CMU", "Carnegie Mellon"],
  "emory-university": ["Emory University", "Emory"],
  georgetown: ["Georgetown University", "Georgetown"],
  "washington-university-in-st-louis": ["Washington University in St. Louis", "WashU", "Washington University St. Louis"],
  bu: ["Boston University", "BU"],
  nyu: ["New York University", "NYU"],
  northeastern: ["Northeastern University", "Northeastern"],
  "george-washington-university": ["George Washington University", "GWU", "GW"],
  "american-university": ["American University", "American"],
  "university-of-miami": ["University of Miami", "Miami", "UM"],
  "tulane-university-of-louisiana": ["Tulane University", "Tulane"],
  smu: ["Southern Methodist University", "SMU"],
  "wake-forest-university": ["Wake Forest University", "Wake Forest"],
  "villanova-university": ["Villanova University", "Villanova"],
  "illinois-state-university": ["Illinois State University", "ISU", "Illinois State"],
  "ball-state-university": ["Ball State University", "Ball State"],
  "western-michigan-university": ["Western Michigan University", "WMU", "Western Michigan"],
  "eastern-michigan-university": ["Eastern Michigan University", "EMU", "Eastern Michigan"],
  "central-michigan-university": ["Central Michigan University", "CMU", "Central Michigan"],
  "northern-illinois-university": ["Northern Illinois University", "NIU", "Northern Illinois"],
  "southern-illinois-university-carbondale": ["Southern Illinois University Carbondale", "SIU Carbondale", "SIU"],
  "indiana-state-university": ["Indiana State University", "Indiana State"],
  "ohio-university": ["Ohio University", "OU Ohio", "OU"],
  "bowling-green-state-university": ["Bowling Green State University", "BGSU", "Bowling Green"],
};

const SCORECARD_SCHOOL_SHORT_NAME_OVERRIDES: Record<string, string> = {
  "uc-berkeley": "UC Berkeley",
  "ut-arlington": "UT Arlington",
  "ut-dallas": "UT Dallas",
  "ut-el-paso": "UT El Paso",
  "ut-san-antonio": "UT San Antonio",
  "ut-tyler": "UT Tyler",
  "ut-rio-grande-valley": "UT Rio Grande Valley",
  "ut-permian-basin": "UT Permian Basin",
  asu: "ASU",
  "ucla": "UCLA",
  "uc-san-diego": "UC San Diego",
  "uc-davis": "UC Davis",
  "uc-irvine": "UC Irvine",
  "uc-riverside": "UC Riverside",
  "uc-santa-barbara": "UC Santa Barbara",
  "uc-santa-cruz": "UC Santa Cruz",
  "uc-merced": "UC Merced",
  "uc-san-francisco": "UC San Francisco",
  brown: "Brown",
  dartmouth: "Dartmouth",
  "western-governors-university": "Western Governors University",
  "southern-new-hampshire-university": "SNHU",
  "grand-canyon-university": "GCU",
  "liberty-university": "Liberty",
  "university-of-phoenix-arizona": "University of Phoenix-Arizona",
  "lone-star-college-system": "Lone Star College",
  "university-of-central-florida": "UCF",
  "florida-international-university": "FIU",
  "university-of-south-florida": "USF",
  "north-carolina-state-university": "NC State",
  "virginia-tech": "Virginia Tech",
  "indiana-university-bloomington": "IU Bloomington",
  "university-of-houston": "University of Houston",
  "university-of-north-texas": "UNT",
  "kennesaw-state-university": "KSU",
  "utah-valley-university": "UVU",
  "florida-state-university": "Florida State",
  "california-state-university-fullerton": "Cal State Fullerton",
  "california-state-university-northridge": "CSUN",
  "university-of-georgia": "University of Georgia",
  "texas-tech-university": "Texas Tech",
  "university-of-alabama": "University of Alabama",
  "texas-state-university": "Texas State",
  "george-mason-university": "George Mason",
  "california-state-university-long-beach": "Cal State Long Beach",
  "michigan-state-university": "Michigan State",
  "georgia-state-university": "Georgia State",
  "miami-dade-college": "Miami Dade College",
  "iowa-state-university": "Iowa State",
  "baylor-university": "Baylor",
  "university-of-arizona": "UArizona",
  "rutgers-university-new-brunswick": "Rutgers",
  "university-of-south-carolina-columbia": "South Carolina",
  "auburn-university": "Auburn",
  "university-at-buffalo": "University at Buffalo",
  "oregon-state-university": "Oregon State",
  "university-of-utah": "The U",
  "university-of-north-carolina-at-charlotte": "UNC Charlotte",
  "east-carolina-university": "ECU",
  "university-of-cincinnati": "University of Cincinnati",
  "university-of-maryland-college-park": "University of Maryland",
  "university-of-kansas": "University of Kansas",
  "university-of-missouri": "University of Missouri",
  "the-university-of-tennessee-knoxville": "University of Tennessee-Knoxville",
  "university-of-kentucky": "University of Kentucky",
  "university-of-oklahoma": "University of Oklahoma",
  "university-of-arkansas": "University of Arkansas",
  "university-of-nevada-las-vegas": "UNLV",
  "university-of-mississippi": "Ole Miss",
  "university-of-delaware": "University of Delaware",
  "university-of-connecticut": "UConn",
  "university-of-nebraska-lincoln": "Nebraska",
  "university-of-new-mexico": "UNM",
  "university-of-alabama-at-birmingham": "UAB",
  "university-of-south-alabama": "South Alabama",
  "university-of-louisville": "Louisville",
  "university-of-idaho": "University of Idaho",
  "university-of-rhode-island": "URI",
  "university-of-maine": "UMaine",
  "university-of-montana": "University of Montana",
  "university-of-wyoming": "University of Wyoming",
  "university-of-alaska-anchorage": "UAA",
  "university-of-alaska-fairbanks": "UAF",
  "university-of-north-dakota": "North Dakota",
  "university-of-south-dakota": "South Dakota",
  "university-of-vermont": "UVM",
  "university-of-new-hampshire": "UNH",
  "university-of-nevada-reno": "UNR",
  "university-of-hawaii-at-manoa": "UH Manoa",
  "university-of-massachusetts-amherst": "UMass Amherst",
  "university-of-massachusetts-lowell": "UMass Lowell",
  "university-of-massachusetts-boston": "UMass Boston",
  "university-of-massachusetts-dartmouth": "UMass Dartmouth",
  "university-of-massachusetts-chan-medical-school": "UMass Chan",
  "university-of-wisconsin-milwaukee": "UW-Milwaukee",
  "university-of-wisconsin-oshkosh": "UW Oshkosh",
  "university-of-wisconsin-eau-claire": "UW-Eau Claire",
  "university-of-wisconsin-la-crosse": "UW-La Crosse",
  "university-of-wisconsin-whitewater": "UW-Whitewater",
  "university-of-wisconsin-green-bay": "UW-Green Bay",
  "university-of-wisconsin-stevens-point": "UW-Stevens Point",
  "university-of-wisconsin-stout": "UW-Stout",
  "university-of-wisconsin-parkside": "UW-Parkside",
  "university-of-wisconsin-river-falls": "UW-River Falls",
  "university-of-wisconsin-superior": "UW-Superior",
  "university-of-wisconsin-platteville": "UW-Platteville",
  "san-jose-state-university": "San Jose State",
  "california-polytechnic-state-university-san-luis-obispo": "Cal Poly SLO",
  "california-state-university-sacramento": "Sac State",
  "california-state-university-san-bernardino": "CSU San Bernardino",
  "california-state-university-fresno": "Fresno State",
  "california-state-university-east-bay": "Cal State East Bay",
  "california-state-university-chico": "Chico State",
  "california-state-university-bakersfield": "CSU Bakersfield",
  "california-state-university-dominguez-hills": "Dominguez Hills",
  "california-state-university-channel-islands": "Channel Islands",
  "california-state-university-monterey-bay": "Monterey Bay",
  "california-state-university-stanislaus": "Stanislaus State",
  "california-state-polytechnic-university-pomona": "Cal Poly Pomona",
  "california-state-university-san-marcos": "CSU San Marcos",
  "california-state-university-los-angeles": "Cal State LA",
  "san-francisco-state-university": "San Francisco State",
  "sonoma-state-university": "Sonoma State",
  "california-state-polytechnic-university-humboldt": "Cal Poly Humboldt",
  "california-state-university-maritime-academy": "Cal Maritime",
  "university-of-the-pacific": "University of the Pacific",
  "santa-clara-university": "Santa Clara",
  "pepperdine-university": "Pepperdine",
  "loyola-marymount-university": "LMU",
  "university-of-san-diego": "University of San Diego",
  "chapman-university": "Chapman",
  "california-institute-of-technology": "Caltech",
  "harvey-mudd-college": "Harvey Mudd",
  "pomona-college": "Pomona",
  "claremont-mckenna-college": "Claremont McKenna",
  "scripps-college": "Scripps",
  "pitzer-college": "Pitzer",
  "university-of-chicago": "UChicago",
  duke: "Duke",
  northwestern: "Northwestern",
  "johns-hopkins": "Johns Hopkins",
  vanderbilt: "Vanderbilt",
  rice: "Rice",
  "notre-dame": "Notre Dame",
  cmu: "CMU",
  "emory-university": "Emory",
  georgetown: "Georgetown",
  "washington-university-in-st-louis": "WashU",
  bu: "BU",
  nyu: "NYU",
  northeastern: "Northeastern",
  "george-washington-university": "George Washington",
  "american-university": "American",
  "university-of-miami": "University of Miami",
  "tulane-university-of-louisiana": "Tulane",
  smu: "SMU",
  "wake-forest-university": "Wake Forest",
  "villanova-university": "Villanova",
  "illinois-state-university": "Illinois State",
  "ball-state-university": "Ball State",
  "western-michigan-university": "Western Michigan",
  "eastern-michigan-university": "Eastern Michigan",
  "central-michigan-university": "Central Michigan",
  "northern-illinois-university": "Northern Illinois",
  "southern-illinois-university-carbondale": "SIU Carbondale",
  "indiana-state-university": "Indiana State",
  "ohio-university": "Ohio University",
  "bowling-green-state-university": "Bowling Green State",
};

export function canonicalScorecardSchoolSlug(rawSlug: string): string {
  return SCORECARD_SCHOOL_SLUG_CANONICAL[rawSlug] ?? rawSlug;
}

function buildAliases(record: ScorecardDirectoryRecord, canonicalSlug: string) {
  const shortName =
    SCORECARD_SCHOOL_SHORT_NAME_OVERRIDES[canonicalSlug] ??
    deriveSchoolShortName(record.name, record.alias);
  return buildSchoolAliases(
    record.name,
    record.alias,
    SCORECARD_SCHOOL_ALIAS_EXTRAS[canonicalSlug] ?? [],
    shortName,
  );
}

function scorecardRecordToSchool(record: ScorecardDirectoryRecord): School {
  const canonicalSlug = canonicalScorecardSchoolSlug(record.slug);
  const shortName =
    SCORECARD_SCHOOL_SHORT_NAME_OVERRIDES[canonicalSlug] ??
    deriveSchoolShortName(record.name, record.alias);

  return {
    id: `scorecard:${record.school_id}`,
    slug: canonicalSlug,
    name: normalizeSchoolText(record.name),
    shortName,
    city: normalizeSchoolText(record.city),
    state: normalizeSchoolText(record.state),
    kind: record.control?.includes("Private") ? "Private" : "Public",
    coverageTier: "rmp_only",
    aliases: buildAliases(record, canonicalSlug),
    directoryCount: 0,
    sourceStatus: {
      primary: "College Scorecard directory",
      fallback: "Rate My Professors",
      freshness: "Directory coverage active",
      note: "This school profile is live. Catalog, schedule, and evidence layers attach as local data is published.",
    },
    supportProfile: {
      plannerReadiness: "directory_ready",
      hasCatalog: false,
      hasSections: false,
      hasInstructorDirectory: false,
      hasPlanner: true,
      hasOfficialGrades: false,
      hasRmp: false,
      hasCommunityEvidence: false,
      evidenceFreshness: "Directory coverage active",
      sourceAvailability: [],
      catalogCompletenessPct: 0,
      sectionCompletenessPct: 0,
      meetingTimeCompletenessPct: 0,
      evidenceCompletenessPct: 0,
      readinessReason:
        "School directory is live, but local catalog and schedule data have not been published yet.",
    },
    descriptor:
      "Universal school profile with the same Classify planning workflow. Course and schedule depth expands as school data is published.",
    programs: [],
  };
}

let scorecardSchoolsCache: School[] | undefined;
let scorecardSchoolsMissingLogged = false;

/** Clears cached Scorecard directory load (e.g. after generating `college_scorecard_schools.json`). */
export function invalidateScorecardDirectoryCache() {
  scorecardSchoolsCache = undefined;
}

/**
 * Reads College Scorecard directory JSON: `etl/output/` (local ETL), then `data/` bundle (deployed),
 * or `SCORECARD_DIRECTORY_JSON_PATH` env override.
 * Returns [] if missing; logs once per process at warn level.
 */
export function loadScorecardDirectorySchools(): School[] {
  if (scorecardSchoolsCache !== undefined) {
    return scorecardSchoolsCache;
  }

  const resolved = resolveScorecardDirectoryJsonFile();
  if (!resolved) {
    if (!scorecardSchoolsMissingLogged) {
      scorecardSchoolsMissingLogged = true;
      console.warn(
        JSON.stringify({
          level: "warn",
          event: "directory_schools_missing",
          tried: [
            process.env.SCORECARD_DIRECTORY_JSON_PATH,
            SCORECARD_DIRECTORY_JSON_PATH,
            SCORECARD_DIRECTORY_DATA_BUNDLE_PATH,
          ].filter(Boolean),
        }),
      );
    }
    scorecardSchoolsCache = [];
    return scorecardSchoolsCache;
  }

  try {
    const payload = JSON.parse(
      fs.readFileSync(resolved, "utf8"),
    ) as ScorecardDirectoryRecord[];

    scorecardSchoolsCache = payload.map(scorecardRecordToSchool);
    return scorecardSchoolsCache;
  } catch (err) {
    console.warn(
      JSON.stringify({
        level: "warn",
        event: "directory_schools_read_failed",
        path: resolved,
        error: String(err),
      }),
    );
    scorecardSchoolsCache = [];
    return scorecardSchoolsCache;
  }
}
