"""Mirror of lib/scorecard-directory canonical slug map (directory slug -> app slug)."""

from __future__ import annotations


SCORECARD_SLUG_CANONICAL: dict[str, str] = {
    "the-university-of-texas-at-austin": "ut-austin",
    "the-university-of-texas-at-arlington": "ut-arlington",
    "the-university-of-texas-at-dallas": "ut-dallas",
    "the-university-of-texas-at-el-paso": "ut-el-paso",
    "the-university-of-texas-at-san-antonio": "ut-san-antonio",
    "the-university-of-texas-at-tyler": "ut-tyler",
    "texas-a-m-university-college-station": "texas-am",
    "the-university-of-texas-rio-grande-valley": "ut-rio-grande-valley",
    "the-university-of-texas-permian-basin": "ut-permian-basin",
    "arizona-state-university-campus-immersion": "asu",
    "university-of-california-berkeley": "uc-berkeley",
    "university-of-wisconsin-madison": "uw-madison",
    "the-ohio-state-university-main-campus": "ohio-state",
    "ohio-state-university-main-campus": "ohio-state",
    "ohio-university-main-campus": "ohio-university",
    "bowling-green-state-university-main-campus": "bowling-green-state-university",
    "north-carolina-state-university-at-raleigh": "north-carolina-state-university",
    "university-of-north-carolina-at-chapel-hill": "unc-chapel-hill",
    "university-of-washington-seattle-campus": "university-of-washington",
    "university-of-illinois-urbana-champaign": "uiuc",
    "georgia-institute-of-technology-main-campus": "georgia-tech",
    "university-of-michigan-ann-arbor": "umich",
    "university-of-california-los-angeles": "ucla",
    "university-of-california-san-diego": "uc-san-diego",
    "university-of-california-davis": "uc-davis",
    "university-of-california-irvine": "uc-irvine",
    "university-of-california-riverside": "uc-riverside",
    "university-of-california-santa-cruz": "uc-santa-cruz",
    "university-of-california-merced": "uc-merced",
    "university-of-california-san-francisco": "uc-san-francisco",
    "university-of-california-santa-barbara": "uc-santa-barbara",
    "the-university-of-alabama": "university-of-alabama",
    "virginia-polytechnic-institute-and-state-university": "virginia-tech",
    "southern-methodist-university": "smu",
    "stanford-university": "stanford",
    "massachusetts-institute-of-technology": "mit",
    "yale-university": "yale",
    "harvard-university": "harvard",
    "duke-university": "duke",
    "northwestern-university": "northwestern",
    "university-of-southern-california": "usc",
    "cornell-university": "cornell",
    "columbia-university-in-the-city-of-new-york": "columbia",
    "university-of-pennsylvania": "upenn",
    "princeton-university": "princeton",
    "brown-university": "brown",
    "dartmouth-college": "dartmouth",
    "johns-hopkins-university": "johns-hopkins",
    "new-york-university": "nyu",
    "carnegie-mellon-university": "cmu",
    "university-of-notre-dame": "notre-dame",
    "vanderbilt-university": "vanderbilt",
    "rice-university": "rice",
    "georgetown-university": "georgetown",
    "university-of-virginia-main-campus": "uva",
    "pennsylvania-state-university-main-campus": "penn-state",
    "purdue-university-main-campus": "purdue",
    "university-of-florida": "uf",
    "university-of-minnesota-twin-cities": "minnesota",
    "arizona-state-university-tempe": "asu",
    "university-of-central-florida": "university-of-central-florida",
    "florida-international-university": "florida-international-university",
    "university-of-south-florida": "university-of-south-florida",
    "indiana-university-bloomington": "indiana-university-bloomington",
    "university-of-houston": "university-of-houston",
    "university-of-north-texas": "university-of-north-texas",
    "kennesaw-state-university": "kennesaw-state-university",
    "utah-valley-university": "utah-valley-university",
    "florida-state-university": "florida-state-university",
    "california-state-university-fullerton": "california-state-university-fullerton",
    "california-state-university-northridge": "california-state-university-northridge",
    "university-of-georgia": "university-of-georgia",
    "texas-tech-university": "texas-tech-university",
    "texas-state-university": "texas-state-university",
    "george-mason-university": "george-mason-university",
    "california-state-university-long-beach": "california-state-university-long-beach",
    "michigan-state-university": "michigan-state-university",
    "georgia-state-university": "georgia-state-university",
    "iowa-state-university": "iowa-state-university",
    "baylor-university": "baylor-university",
    "university-of-arizona": "university-of-arizona",
    "rutgers-university-new-brunswick": "rutgers-university-new-brunswick",
    "university-of-south-carolina-columbia": "university-of-south-carolina-columbia",
    "auburn-university": "auburn-university",
    "university-at-buffalo": "university-at-buffalo",
    "oregon-state-university": "oregon-state-university",
    "university-of-utah": "university-of-utah",
    "university-of-north-carolina-at-charlotte": "university-of-north-carolina-at-charlotte",
    "east-carolina-university": "east-carolina-university",
    "university-of-cincinnati-main-campus": "university-of-cincinnati",
    "university-of-maryland-college-park": "university-of-maryland-college-park",
    "university-of-kansas": "university-of-kansas",
    "university-of-missouri-columbia": "university-of-missouri",
    "the-university-of-tennessee-knoxville": "the-university-of-tennessee-knoxville",
    "university-of-kentucky": "university-of-kentucky",
    "university-of-oklahoma-norman-campus": "university-of-oklahoma",
    "university-of-arkansas": "university-of-arkansas",
    "university-of-nevada-las-vegas": "university-of-nevada-las-vegas",
    "university-of-mississippi": "university-of-mississippi",
    "university-of-colorado-boulder": "cu-boulder",
    "university-of-iowa": "iowa",
    "boston-university": "bu",
    "northeastern-university": "northeastern",
    "the-university-of-montana": "university-of-montana",
    "university-of-new-mexico-main-campus": "university-of-new-mexico",
    "university-of-new-hampshire-main-campus": "university-of-new-hampshire",
    "university-of-massachusetts-medical-school-worcester":
        "university-of-massachusetts-chan-medical-school",
}


def canonical_app_school_slug(directory_slug: str) -> str:
    return SCORECARD_SLUG_CANONICAL.get(directory_slug, directory_slug)
